CREATE TABLE rental_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id bigint NOT NULL REFERENCES rentals (id),
    kind text NOT NULL CHECK (kind IN ('base', 'overdue', 'refund')),
    amount_kopecks bigint NOT NULL CHECK (amount_kopecks > 0),
    occurred_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_user_id bigint NOT NULL REFERENCES users (id),
    related_payment_id bigint REFERENCES rental_payments (id),
    CONSTRAINT rental_payments_relation_check CHECK (
        (kind = 'refund' AND related_payment_id IS NOT NULL)
        OR (kind IN ('base', 'overdue') AND related_payment_id IS NULL)
    )
);

CREATE UNIQUE INDEX rental_payments_one_base_per_rental
    ON rental_payments (rental_id) WHERE kind = 'base';
CREATE UNIQUE INDEX rental_payments_one_overdue_per_rental
    ON rental_payments (rental_id) WHERE kind = 'overdue';
CREATE UNIQUE INDEX rental_payments_one_refund_per_payment
    ON rental_payments (related_payment_id) WHERE kind = 'refund';
CREATE INDEX rental_payments_rental_id_id_idx ON rental_payments (rental_id, id);

---- create above / drop below ----

DROP TABLE rental_payments;
